export const SERVER_URL = "https://worldcerts.herokuapp.com/"
export const LOGIN_USER = SERVER_URL + "login/"
export const SIGN_UP_USER = SERVER_URL + "signup/"
export const REGISTER_INSTITUTE = SERVER_URL + "institute/"
export const USER = SERVER_URL + "verifyUser/"
export const UPDATE_USER = SERVER_URL + "userUpdate/"
export const CLASSIFICATION = SERVER_URL + "classification/"
export const GET_REGISTERED_INSTITUTES = SERVER_URL + "getUserRegisteredInstitutes/"
