export const PASSWORD_NOT_MATCHED = "Password not matched"
export const EMAIL_PASSWORD_INCORRECT = "Email or password is incorrect"
export const INVALID_PASSWORD = "Invalid password"
export const DATA_UPDATED = "Data has been updated"
export const DATA_NOT_UPDATED = "Data has not been updated"
export const ALL_FIELDS_REQUIRED = "All fields are required"
export const REGISTRATION_NUMBER_EXISTS = "Registration number already exists"
export const REGISTRATION_NUMBER_LONG = "Registration number is too long"
export const REQUEST_SENT = "Request sent"
export const CODE_NOT_EMPTY = "Code must not be empty"
export const INSTITUTE_REGISTRATION = "institute_registration"
export const WORLDCERTS = "Worldcerts"
export const REDUX = "Redux =>"
export const EMAIL_NOT_FOUND = "Email not found"
export const EMAIL_ALREADY_EXISTS = "Email already exists"
export const USER_NOT_REGISTERED = "User not registered"
export const INSTITUTE_MANAGEMENT="manageInstitute"
